# Generated by Django 2.2.1 on 2019-09-18 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('decreasing_color', models.CharField(choices=[['#00008b', 'blue'], ['#d00631', 'red'], ['#006400', 'green'], ['#ff00ff', 'pink'], ['#8a2be2', 'purple'], ['#ff6600', 'orange'], ['#a0522d', 'brown'], ['#daa520', 'gold'], ['#000000', 'black'], ['#12FEFF', 'cyan'], ['#08FE04', 'lime']], max_length=20)),
                ('increasing_color', models.CharField(choices=[['#00008b', 'blue'], ['#d00631', 'red'], ['#006400', 'green'], ['#ff00ff', 'pink'], ['#8a2be2', 'purple'], ['#ff6600', 'orange'], ['#a0522d', 'brown'], ['#daa520', 'gold'], ['#000000', 'black'], ['#12FEFF', 'cyan'], ['#08FE04', 'lime']], max_length=20)),
                ('line_color', models.CharField(choices=[['#00008b', 'blue'], ['#d00631', 'red'], ['#006400', 'green'], ['#ff00ff', 'pink'], ['#8a2be2', 'purple'], ['#ff6600', 'orange'], ['#a0522d', 'brown'], ['#daa520', 'gold'], ['#000000', 'black'], ['#12FEFF', 'cyan'], ['#08FE04', 'lime']], max_length=20)),
                ('period', models.CharField(choices=[('d', 'Daily'), ('w', 'Weekly')], default='d', max_length=30)),
            ],
            options={
                'verbose_name': 'Chart',
            },
        ),
        migrations.CreateModel(
            name='ChartIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('param', models.IntegerField(default=0)),
                ('position', models.CharField(choices=[('1', 'Above'), ('2', 'Behind Price'), ('3', 'Below')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChartOverlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('param', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.Chart')),
            ],
            options={
                'verbose_name': 'List',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(null=True)),
                ('universe', models.CharField(max_length=50)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chart.Chart')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.List')),
            ],
            options={
                'verbose_name': 'Instrument',
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='indicator',
            field=models.ManyToManyField(to='chart.ChartIndicator'),
        ),
        migrations.AddField(
            model_name='chart',
            name='overlay',
            field=models.ManyToManyField(to='chart.ChartOverlay'),
        ),
        migrations.AddField(
            model_name='chart',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.ChartType'),
        ),
        migrations.AddField(
            model_name='chart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
