# Generated by Django 2.2.1 on 2019-12-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0027_auto_20191203_1045'),
        ('optimize', '0002_buystrategy_periodstrategy_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodstrategy',
            name='buystrategy',
        ),
        migrations.AddField(
            model_name='periodstrategy',
            name='strategy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_strategy', to='backtest.Strategy'),
        ),
        migrations.DeleteModel(
            name='BuyStrategy',
        ),
    ]
