# Generated by Django 2.2.1 on 2019-11-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adx',
            name='period',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='atrn',
            name='period',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='ema',
            name='period',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='roc',
            name='period',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='rsi',
            name='period',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='slope',
            name='period',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='sma',
            name='period',
            field=models.IntegerField(default=50),
        ),
    ]
