# Generated by Django 2.2.1 on 2019-11-05 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_auto_20191105_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adx',
            options={'verbose_name': 'Average Directional Index'},
        ),
    ]
