# Generated by Django 2.2.1 on 2019-11-05 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0003_auto_20191105_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adx',
            options={'base_manager_name': 'objects'},
        ),
    ]
