# Generated by Django 2.2.1 on 2019-11-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0004_auto_20191105_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('definition', models.TextField(max_length=200)),
            ],
        ),
    ]
