# Generated by Django 2.2.1 on 2019-11-07 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0008_auto_20191107_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='liquidity_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.Liquidity_System'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='rank_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.Ranking_System'),
        ),
    ]
