# Generated by Django 2.2.1 on 2019-11-11 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0009_auto_20191107_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators_Combination',
            fields=[
                ('indicator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backtest.Indicator')),
                ('coeff', models.DecimalField(decimal_places=5, default=1.0, max_digits=10)),
                ('operator', models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/')], max_length=3, verbose_name='Operator')),
                ('indicator1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_comb_1', to='backtest.Indicator')),
                ('indicator2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_comb_2', to='backtest.Indicator')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('backtest.indicator',),
        ),
    ]
