# Generated by Django 2.2.1 on 2019-11-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0013_auto_20191116_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinationstrategy',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=10, null=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='combinationstrategy',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('Long', 'Long')], max_length=10, null=True, verbose_name='Transaction Type'),
        ),
    ]
