# Generated by Django 2.2.1 on 2019-11-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0016_auto_20191125_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinationstrategy',
            name='strategy',
            field=models.ManyToManyField(related_name='strategys', to='backtest.Strategy'),
        ),
        migrations.DeleteModel(
            name='SubField',
        ),
    ]
