# Generated by Django 2.2.1 on 2019-11-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0017_auto_20191125_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinationstrategy',
            name='strategy',
        ),
        migrations.CreateModel(
            name='BuyStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to='backtest.Strategy')),
            ],
        ),
        migrations.AddField(
            model_name='combinationstrategy',
            name='buystrategy',
            field=models.ManyToManyField(related_name='buy_strategys', to='backtest.BuyStrategy'),
        ),
    ]
