# Generated by Django 2.2.1 on 2019-11-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0019_buystrategy_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinationstrategy',
            name='state',
            field=models.CharField(default='red', max_length=10),
        ),
    ]
