# Generated by Django 2.2.1 on 2019-11-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0020_combinationstrategy_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='buystrategy',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
