# Generated by Django 2.2.1 on 2019-11-25 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0021_buystrategy_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinationstrategy',
            name='results',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backtest.Result'),
        ),
    ]
