# Generated by Django 2.2.1 on 2019-11-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0022_auto_20191125_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=10, null=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='rank_rebalance_type',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Never', 'Never')], max_length=10, null=True, verbose_name='Ranking system rebalance'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('Long', 'Long')], max_length=10, null=True, verbose_name='Transaction Type'),
        ),
    ]
