# Generated by Django 2.2.1 on 2019-12-02 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0024_auto_20191126_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='benchmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.Benchmarks_Tree'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='universe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.Universe_Tree'),
        ),
    ]
