# Generated by Django 2.2.1 on 2019-12-03 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0026_auto_20191202_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinationstrategy',
            name='benchmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.Benchmarks_Tree'),
        ),
        migrations.AlterField(
            model_name='combinationstrategy',
            name='universe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.Universe_Tree'),
        ),
    ]
