# Generated by Django 2.2.1 on 2019-11-08 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20191107_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators_combination_system',
            name='default_combination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_combination', to='backtest.Indicator'),
        ),
    ]
