# Generated by Django 2.2.1 on 2019-11-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0010_indicators_combination'),
        ('tools', '0005_auto_20191109_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicators_combination_folder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='indicators_combination_system',
            name='default_combination',
        ),
        migrations.RemoveField(
            model_name='indicators_combination_system',
            name='user',
        ),
        migrations.RemoveField(
            model_name='indicators_combination_tree',
            name='user',
        ),
        migrations.AlterField(
            model_name='ranking_rule',
            name='direction',
            field=models.CharField(choices=[('LB', 'Lower is better'), ('HB', 'Higher is better')], max_length=20, verbose_name='Direction'),
        ),
        migrations.DeleteModel(
            name='Indicators_Combination',
        ),
        migrations.DeleteModel(
            name='Indicators_Combination_Folder',
        ),
        migrations.DeleteModel(
            name='Indicators_Combination_System',
        ),
        migrations.DeleteModel(
            name='Indicators_Combination_Tree',
        ),
    ]
